# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/notifications
Accept: application/json

###

POST http://127.0.0.1:8000/send-notification/{{ $random.email }}
Content-Type: application/json
